location: East US
locationShort: eastus
environment: production
environmentShort: prd
rgCommonName: paloalto
vnetResourceGroupName: RG-ansible-palo
vnetName: VNET-ansible-palo-alto
commonName: paloalto
commonNameShort: pa