- hosts: azure
  environment:
    AZURE_CLIENT_ID: "{{ AZURE_CLIENT_ID }}"
    AZURE_SECRET: "{{ AZURE_SECRET }}"
    AZURE_SUBSCRIPTION_ID: "{{ AZURE_SUBSCRIPTION_ID }}"
    AZURE_TENANT: "{{ AZURE_TENANT }}"
  tasks:  
    - name: Create virtual machine
      azure_rm_virtualmachine:
      resource_group: RG-ansible-palo
      name: ansibletestvm10
      vm_size: Standard_D1
      admin_username: azureuser
      ssh_password_enabled: false
      admin_password: Password!
      image:
        offer: CentOS
        publisher: OpenLogic
        sku: '7.1'
        version: latest  
      