- name: Wait for FW to respond
  panos_check:
    ip_address: "{{ ip_address }}"
    username: "{{ username }}"
    password: "{{ password }}"
  register: result
  until: not result|failed
  retries: 50
  delay: 5  